### ISSUE TITLE
implement function load_arrays() (to use in viewer only)

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#276]
It appears that some users would like to have a function that does same thing as edit() does: 
search for all existing LArray objects and create a Session + save it.

Same with a 'load_arrays' function : load a Session and put all arrays in the current namespace.

**Comment by gdementen** [comment]
* unsure having save_arrays() is worth it when we already have local_arrays().save()
* load_arrays() should be implemented so that we can do the equivalent of File->Open via the console, but we should make it clear in the documentation that it should only ever be used in an interactive console and **not** in a script (because in we lose the ability to track where each variable comes from).

**Comment by alixdamman** [comment]
I didn't know local_arrays() already exist. Now I know. Sorry.

**Comment by gdementen** [comment]
np :)

**Comment by alixdamman** [comment]
The function is not documented. Is there a reason for that (users should not use it)?

**Comment by gdementen** [comment]
Just an oversight I guess.
